#+include: templates/header.org
* About me

My name is Alejandro Gallo and I am currently a physicist at the
Technical University of Vienna [[https://cqc.itp.tuwien.ac.at]].

I work in the interface between condensed matter physics, quantum
chemistry and software engineering.

* Publications

#+include: publications.org

* Software

I am the author of several scientific packages like [[https://github.com/cc4s/cc4s][CC4S]], my
personal [[https://github.com/cc4s/cc4s][SISI4S]] and a high-performance kernel for the =CCSD(T)=
algorithm [[https://alejandrogallo.github.io/atrip/atrip.html][ATRIP]] with on-going CUDA support.

I enjoy building many things, be it on the computer or with my hands.
Maybe check out my [[https://github.com/alejandrogallo][github]] profile for some examples [[https://github.com/alejandrogallo][here]].
- I am the main author and maintainer of [[https://github.com/papis/papis][papis]].
- I try to optimize my keyboard layout
  in [[https://github.com/alejandrogallo/split-atreus/][the split keyboard lab]]. and the [[https://github.com/alejandrogallo/luakh-keymap][QMK לוח]] keymap.
- I build my own [[https://github.com/alejandrogallo/dikis][dictionaries]] for [[https://github.com/alejandrogallo/python-milon][hebrew]] and [[https://github.com/alejandrogallo/aramorph][arabic]].


* Music
- I had much fun playing in Baasztian's album
  [[https://baasztian.bandcamp.com/album/diagnose-chronisch-ironisch][diagnose: chronisch ironisch]].
- I released a demo back in 2006 called *Open 24 Hours*
  under the artistic name of *Nango*, you can check out the bandcamp
  [[https://nango.bandcamp.com][here]].
