baseURL: 'https://alejandrogallo.github.io/blog'
languageCode: 'en-us'
title: "Ale's Ecke"
theme: 'PaperMod'

markup.goldmark.renderer:
  unsafe: true

params:
  env: production
  title: "Ale's Ecke"
  description: "A blog about science, technology and thoughts"
  keywords: [Blog, Portfolio, Science, QuantumChemistry, Raku, Lisp, Haskell,
             DFT, Hartree-Fock]
  author: "Alejandro Gallo"
  #images: []
  defaultTheme: auto # dark, light
  disableThemeToggle: false
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  # disableSpecial1stPost: false
  # disableScrollToTop: false
  # comments: true
  # hidemeta: false
  # hideSummary: true
  showtoc: true
  # tocopen: false

  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

  socialIcons:
  #   github: "https://github.com/alejandrogallo"
  #   googlescholar: "https://github.com"

  # profileMode:
  #   enabled: true
  #   title: "<Title>" # optional default will be site title
  #   subtitle: "This is subtitle"
  #   imageUrl: "<image link>" # optional
  #   imageTitle: "<title of image as alt>" # optional
  #   imageWidth: 120 # custom size
  #   imageHeight: 120 # custom size
  #   buttons:
  #       - name: Archive
  #         url: "/archive"
  #       - name: Github
  #         url: "https://github.com/alejandrogallo/"



author:
  name: "Alejandro Gallo"
  email: "aamsgallo@gmail.com"

social:
  github: "alejandrogallo"
  googlescholar: "alejandrogallo"

menu:
  main:
    - identifier: posts
      name: posts
      url: /posts/
      weight: 10
    - identifier: tags
      name: tags
      url: /tags/
      weight: 10
    - identifier: search
      name: search
      url: /search/
      weight: 20
    # - identifier: categories
    #   name: categories
    #   url: /categories/
    #   weight: 10
